import type { VersionUpdate } from "./types";
import { dedent } from "@luxass/utils";
import { Eta } from "eta";
import farver from "farver";
import { logger } from "./utils";

interface SharedGitHubOptions {
  owner: string;
  repo: string;
  githubToken: string;
}

interface GitHubPullRequest {
  number: number;
  title: string;
  body: string;
  draft: boolean;
  html_url?: string;
}

export async function getExistingPullRequest({
  owner,
  repo,
  branch,
  githubToken,
}: SharedGitHubOptions & {
  branch: string;
}): Promise<GitHubPullRequest | null> {
  try {
    logger.debug(`Requesting pull request for branch: ${branch} (url: https://api.github.com/repos/${owner}/${repo}/pulls?state=open&head=${branch})`);
    const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls?state=open&head=${branch}`, {
      headers: {
        Accept: "application/vnd.github.v3+json",
        Authorization: `token ${githubToken}`,
      },
    });

    if (!res.ok) {
      throw new Error(`GitHub API request failed with status ${res.status}`);
    }

    const pulls = await res.json();

    if (pulls == null || !Array.isArray(pulls) || pulls.length === 0) {
      return null;
    }

    const firstPullRequest: unknown = pulls[0];

    if (
      typeof firstPullRequest !== "object"
      || firstPullRequest === null
      || !("number" in firstPullRequest)
      || typeof firstPullRequest.number !== "number"
      || !("title" in firstPullRequest)
      || typeof firstPullRequest.title !== "string"
      || !("body" in firstPullRequest)
      || typeof firstPullRequest.body !== "string"
      || !("draft" in firstPullRequest)
      || typeof firstPullRequest.draft !== "boolean"
      || !("html_url" in firstPullRequest)
      || typeof firstPullRequest.html_url !== "string"
    ) {
      throw new TypeError("Pull request data validation failed");
    }

    const pullRequest: GitHubPullRequest = {
      number: firstPullRequest.number,
      title: firstPullRequest.title,
      body: firstPullRequest.body,
      draft: firstPullRequest.draft,
      html_url: firstPullRequest.html_url,
    };

    logger.info(`Found existing pull request: ${farver.yellow(`#${pullRequest.number}`)}`);

    return pullRequest;
  } catch (err) {
    logger.error("Error fetching pull request:", err);
    return null;
  }
}

export async function upsertPullRequest({
  owner,
  repo,
  title,
  body,
  head,
  base,
  pullNumber,
  githubToken,
}: SharedGitHubOptions & {
  title: string;
  body: string;
  head?: string;
  base?: string;
  pullNumber?: number;
}): Promise<GitHubPullRequest | null> {
  try {
    const isUpdate = pullNumber != null;
    const url = isUpdate
      ? `https://api.github.com/repos/${owner}/${repo}/pulls/${pullNumber}`
      : `https://api.github.com/repos/${owner}/${repo}/pulls`;

    const method = isUpdate ? "PATCH" : "POST";

    const requestBody = isUpdate
      ? { title, body }
      : { title, body, head, base };

    logger.debug(`${isUpdate ? "Updating" : "Creating"} pull request (url: ${url})`);
    const res = await fetch(url, {
      method,
      headers: {
        Accept: "application/vnd.github.v3+json",
        Authorization: `token ${githubToken}`,
      },
      body: JSON.stringify(requestBody),
    });

    if (!res.ok) {
      throw new Error(`GitHub API request failed with status ${res.status}`);
    }

    const pr = await res.json();

    if (
      typeof pr !== "object"
      || pr === null
      || !("number" in pr)
      || typeof pr.number !== "number"
      || !("title" in pr)
      || typeof pr.title !== "string"
      || !("body" in pr)
      || typeof pr.body !== "string"
      || !("draft" in pr)
      || typeof pr.draft !== "boolean"
      || !("html_url" in pr)
      || typeof pr.html_url !== "string"
    ) {
      throw new TypeError("Pull request data validation failed");
    }

    const action = isUpdate ? "Updated" : "Created";
    logger.info(`${action} pull request: ${farver.yellow(`#${pr.number}`)}`);

    return {
      number: pr.number,
      title: pr.title,
      body: pr.body,
      draft: pr.draft,
      html_url: pr.html_url,
    };
  } catch (err) {
    logger.error(`Error upserting pull request:`, err);
    throw err;
  }
}

const defaultTemplate = dedent`
  This PR was automatically generated by the release script.

  The following packages have been prepared for release:

  <% it.packages.forEach((pkg) => { %>
  - **<%= pkg.name %>**: <%= pkg.currentVersion %> → <%= pkg.newVersion %> (<%= pkg.bumpType %>)
  <% }) %>

  Please review the changes and merge when ready.

  For a more in-depth look at the changes, please refer to the individual package changelogs.

  > [!NOTE]
  > When this PR is merged, the release process will be triggered automatically, publishing the new package versions to the registry.
`;

function dedentString(str: string): string {
  const lines = str.split("\n");
  const minIndent = lines
    .filter((line) => line.trim().length > 0)
    .reduce((min, line) => Math.min(min, line.search(/\S/)), Infinity);

  return lines
    .map((line) => (minIndent === Infinity ? line : line.slice(minIndent)))
    .join("\n")
    .trim();
}

export function generatePullRequestBody(updates: VersionUpdate[], body?: string): string {
  const eta = new Eta();

  const bodyTemplate = body ? dedentString(body) : defaultTemplate;

  return eta.renderString(bodyTemplate, {
    packages: updates.map((u) => ({
      name: u.package.name,
      currentVersion: u.currentVersion,
      newVersion: u.newVersion,
      bumpType: u.bumpType,
      hasDirectChanges: u.hasDirectChanges,
    })),
  });
}
