name: GitHub Actions Security Analysis

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - ".github/workflows/**"
  push:
    branches:
      - main
      - "renovate/**"
    paths:
      - ".github/workflows/**"

permissions: {}

jobs:
  zizmor:
    uses: luxass/shared-workflows/.github/workflows/ci-security.yaml@56bd9148cc90ee377d1e6fa3a32e43d18859dfe1 # v0.4.2
    permissions:
      contents: read
      security-events: write
      id-token: write
    with:
      zizmor-version: v1.23.1
