name: GitHub Actions Security Analysis

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - ".github/workflows/**"
  push:
    branches:
      - main
      - "renovate/**"
    paths:
      - ".github/workflows/**"

permissions: {}

jobs:
  zizmor:
    uses: luxass/shared-workflows/.github/workflows/ci-security.yaml@1da57045a6e7f913231d1edfb21d95de9e3eeaad # v0.4.1
    permissions:
      contents: read
      security-events: write
      id-token: write
    with:
      zizmor-version: v1.23.1
