name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

permissions: {}

jobs:
  ci:
    uses: luxass/shared-workflows/.github/workflows/ci.yaml@1da57045a6e7f913231d1edfb21d95de9e3eeaad # v0.4.1
    permissions:
      contents: read
    with:
      fmt: true
      fmt-script: "fmt:check"

  test:
    uses: luxass/shared-workflows/.github/workflows/test.yaml@1da57045a6e7f913231d1edfb21d95de9e3eeaad # v0.4.1
    permissions:
      contents: read
